Feat/unit test setup
njallskarp/finetune-qa-powerset pull request #45
Opened 2023-06-29 17:32 UTC by eysta00

# Units tests and Github Actions for running tests
Adding unit tests and github actions such that when any one of us pushes or pulls to dev we have to pass the unit tests.

# How to test

- run `poetry run pytest` in your console in the root folder of the project.
- automatic linting with GHA

2023-06-29 22:21 UTC, lsig commented on .github/workflows/test.yml
> +      - run: poetry install --no-interaction
Remove this run command, fails because poetry already installed

2023-06-30 10:08 UTC, eysta00 commented
The GHA seems to be working correctly now but I just need the import to work correctly now in the test file itself

2023-06-30 12:14 UTC, eysta00 commented
It seems that adding __init__.py to **Every** directory fixes the problem regarding imports and also removing **all** relative imports, additionally we have to rename the types folder since by adding a __init__.py it becomes a package and tries to overwrite an existing python package so I propose to rename that folder to 'typings' but we could also do 'definitions'.

The way I am solving this problem doesn't seem right but it does get the tests running

2023-06-30 13:35 UTC, njallskarp commented
Really great addition to the codebase @eysta00, adding a few comments for improvements.

2023-06-30 13:37 UTC, njallskarp requested changes
see comments

2023-06-30 13:39 UTC, njallskarp requested changes

2023-06-30 13:39 UTC, njallskarp commented on tests/training_test/metrics_test.py
> +def test_precision():
two things to improve

1) instead of just testing words.. try to think of more cases. Normal cases such as sentences, what about empty strings? Empty predictions, both empty? Also don't only test edge cases.. test also the 'normal cases'

2023-06-30 13:43 UTC, eysta00 commented on tests/training_test/metrics_test.py
> +def test_precision():
valuable feedback! I will write these improved tests as soon I fix the issue regarding my workflow with GHA, seems like missing GPU libraries on the bot that runs the actions

2023-06-30 13:48 UTC, njallskarp commented on tests/training_test/metrics_test.py
> +def test_precision():
OK. Let me know if that remains an issue. I'm curious whether or not it would be possible for us to run the unit tests without needing to use or call any libraries / packages needing a GPU.

Keep me in the loop if you need to discuss this further

2023-06-30 13:56 UTC, eysta00 commented on tests/training_test/metrics_test.py
> +def test_precision():
so after a little bit of googling and asking AI friends this seems to be the problem;

> Please note that GitHub-hosted runners do not have GPU hardware. Therefore, even if you install the CUDA toolkit, you won't be able to run GPU-accelerated computations on GitHub-hosted runners. If you need to run GPU-accelerated computations as part of your GitHub Actions workflow, you'll need to use self-hosted runners with GPU hardware.

So if we use self-hosted runners we can use GPU hardware there and then test the ML model continuously.

2023-06-30 14:00 UTC, njallskarp commented on tests/training_test/metrics_test.py
> +def test_precision():
Is it possible to do the tests without testing the model? If we just test the functions (on a unit level) that should be sufficient for this time being

2023-06-30 14:08 UTC, eysta00 commented on tests/training_test/metrics_test.py
> +def test_precision():
I think we are already doing that
As it stands we are only running tests on f1, precision and recall. They are all completely independent from the model.

The case might just be that we are importing from the transformers package and that in of itself is causing the problem.

Perhaps we need to decouple the metric functions in metric.py and isolate the evaluate_model function

2023-06-30 15:28 UTC, njallskarp commented on tests/training_test/metrics_test.py
> +def test_precision():
Ok I see. I'm pretty sure that transformers should run on a CPU only system. It is possible that they need tensorflow and pytorch as dependencies as well.  Try running the tests on your machine, does that work?

2023-06-30 15:30 UTC, njallskarp commented on tests/training_test/metrics_test.py
> +def test_precision():
Additional thought: what happens if you comment out the `evaluate_model` function in metrics.py?

2023-06-30 15:45 UTC, eysta00 commented on tests/training_test/metrics_test.py
> +def test_precision():
Yes, running the tests locally works without issues :)

2023-06-30 15:49 UTC, eysta00 commented on tests/training_test/metrics_test.py
> +def test_precision():
Also, I am pretty sure that `poetry install --no-interaction --no-root` should install all our dependencies

2023-06-30 15:56 UTC, eysta00 commented on .github/workflows/tests.yml
> +        run: poetry run pytest --rootdir=tests
Regarding problems with github actions, perhaps writing in this thread would be better

2023-07-06 14:26 UTC, eysta00 commented
Kinda stuck on this problem of when importing pytorch, no matter what, I get an import error in the github action workflow.

Honestly the way to fix this just momentarily is to decouple the evaluate_model function from metrics.py, but that won't fix the underlying problem of Github Actions having none of the CUDA libraries, been stuck on this for the last two days.

Going to come back to this in the evening and rework the actual tests to just be better.

If we run our own Github Actions server with a GPU then this should be no problem but that is also a whole new can of worms.

2023-07-20 13:24 UTC, eysta00 commented
Managed to get Pytorch to import correctly using the CPU version of Pytorch, however now there seems to be some version incompatibilities with importing the RobertaForQuestionAnswering transformer

2023-08-03 13:31 UTC, closed without merging