Feat/validate, made validations function for model
njallskarp/finetune-qa-powerset pull request #6
Opened 2023-06-26 21:56 UTC by lsig

validation function made and type annotated, need to make evaluate model function in metrics.py and also would be nice to extract get_prediction into a utils file since the function is used in both validate and train.

2023-06-26 23:28 UTC, njallskarp commented on training/validate.py
> +def get_prediction(model: PreTrainedModel, batch: DataLoader[tuple[torch.Tensor, torch.Tensor]]) -> PreTrainedModel:
This is the same function, let's reuse. Possibly by having get_prediction, validate, and train all in the same file.

Also, is PreTrainedModel the right type declaration, I'm wondering if there is a similar type that is more indicative of what the function is actually outputting.. i.e. prediction output

2023-06-26 23:29 UTC, njallskarp requested changes
Added one comment  on get_prediction

Looks good but lets restructure code because of D.R.Y.

2023-06-27 09:19 UTC, njallskarp commented on training/validate.py
> +    #TODO: need to make evaluate_model function
Remove this TODO

2023-06-27 09:21 UTC, njallskarp requested changes
Adding request for changes

2023-06-27 09:21 UTC, njallskarp commented on training/validate.py
> +
Add """ """ multiline comment documenting function

2023-06-27 09:21 UTC, njallskarp commented on training/validate.py
> +
comment """ """ here too

2023-06-27 09:21 UTC, njallskarp commented on training/validate.py
> +device = torch.device("cpu:0" if torch.cuda.is_available() else "cpu")
Let's take this out of global scope and put it under `get_rediction`

2023-06-27 10:25 UTC, njallskarp commented on training/validate.py
> +def get_prediction(model: PreTrainedModel, batch: DataLoader[tuple[torch.Tensor, torch.Tensor]]) -> PreTrainedModel:
Check out docs for the forward method here: https://huggingface.co/transformers/v3.0.2/model_doc/bert.html#transformers.BertForQuestionAnswering.forward

Return type is `tuple(torch.FloatTensor)`

2023-06-27 10:51 UTC, lsig commented on training/validate.py
> +    #TODO: need to make evaluate_model function
This function is something that still needs to be implemented, will remove when that work has finished. 💯

2023-06-27 13:51 UTC, eysta00 commented on training/utils.py
> +def get_rediction() -> device:
This should possible be a private function; i.e. __get_rediction() -> device:

2023-06-27 13:53 UTC, eysta00 approved these changes
looks good overall

2023-06-27 14:40 UTC, njallskarp commented on types/declarations.py
> +    answers_end: int
Add a """ """ explaining the type

2023-06-28 09:24 UTC, njallskarp requested changes

2023-06-28 09:29 UTC, njallskarp approved these changes

2023-06-28 09:29 UTC, merged