Update __init__.py
njallskarp/finetune-qa-powerset pull request #9
Opened 2023-06-27 10:15 UTC by eysta00

added 1 folder, 2 files: "__init__.py" and "config.py" and a small class to __init__.py.
Config.py my be unnecessary at the current time.

2023-06-27 13:15 UTC, njallskarp commented on training_datasets/__init__.py
> +class SquadDataset(torch.utils.data.Dataset):
Refactor this

2023-06-27 13:15 UTC, njallskarp requested changes
Create a datasets.py module and put the Dataset class in there

2023-06-27 13:48 UTC, eysta00 commented
organized imports*

2023-06-27 14:09 UTC, lsig commented
I was wondering if you could format the docstrings so they are inline, otherwise looks good. Maybe I can setup a formatter.

2023-06-27 14:38 UTC, njallskarp requested changes
see comment. Need to improve typing

2023-06-27 14:38 UTC, njallskarp commented on training_datasets/datasets.py
> +    def __init__(self, encodings: any, is_train: bool = True):
Add types, check in with @lsig if you need details on the types.

2023-06-27 14:39 UTC, njallskarp requested changes
fix nesting of classes

2023-06-27 14:39 UTC, njallskarp commented on training_datasets/datasets.py
> +    Code reused from open source colab notebook:
Class should not be nested, please review and fix

2023-06-27 14:40 UTC, eysta00 commented
@lsig what is the type for encodings?

2023-06-28 09:43 UTC, eysta00 commented
> Collaborator
@lsig https://github.com/njallskarp/finetune-qa-powerset/pull/9#issuecomment-1609587840
are you talking about docstring comments beginning like this:
`""" Some text begins here

Args:
   The arguments

Returns:
    arguments added together`

2023-06-28 10:15 UTC, lsig commented on training_datasets/datasets.py
> +    def __init__(self, encodings: any, is_train: bool = True):
Let me check

2023-06-28 10:18 UTC, lsig commented on training_datasets/datasets.py
> +    def __init__(self, encodings: any, is_train: bool = True):
It is the return type of tokenizer

2023-06-28 10:57 UTC, lsig commented on training_datasets/datasets.py
> +    def __init__(self, encodings: any, is_train: bool = True):
Probably Tokenzier().encodings or something like that

2023-06-28 12:13 UTC, closed without merging